name = "InShittingRev2"
author = "CanInBad"
version = "a11"
description = "A general modpack \"designed\" to be light, easy to run on potato, and fun!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "929afc0627b4ab8cfca61b6b944781baf17396e8c639b2184597009b21f19aae"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"
