name = "InShittingRev2"
author = "CanInBad"
version = "a0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b491329b90ea88e59a770dbe3136e3842fe34b6dbe8d099c837a64d26dbfe06a"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"
