name = "InShittingRev2"
author = "CanInBad"
version = "a8"
description = "A general modpack \"designed\" to be light, easy to run on potato, and fun!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cac3a7dc39ff03bdd54668e05bcbef5a30c1d0399390db51915190c38f5852a9"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"
