name = "InShittingRev2"
author = "CanInBad"
version = "a7"
description = "A general modpack \"designed\" to be light, easy to run on potato, and fun!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9020e8caee8ce60ed90d96c485ca50daecbd81afa5b8810fa2e72f174d1ad249"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"
