name = "InShittingRev2"
author = "CanInBad"
version = "a5"
description = "A general modpack \"designed\" to be light, easy to run on potato, and fun!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c32a3fd8dceb0a6b9f4011b8d1c6bc5b8a83b6d7ca8efd8c12a39f2708e8d95"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"
