name = "InShittingRev2"
author = "CanInBad"
version = "a13"
description = "A general modpack \"designed\" to be light, easy to run on potato, and fun!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ebad15f37b16a08bfae2d8227f6457895e890b99b33c5894815e104e903c320"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"
