name = "InShittingRev2"
author = "CanInBad"
version = "a6"
description = "A general modpack \"designed\" to be light, easy to run on potato, and fun!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3172bb39d5d2e57971a859e52feb76caffe1fa7421b8797bb0ad0bd78c84e6c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"
