name = "InShittingRev2"
author = "CanInBad"
version = "a9"
description = "A general modpack \"designed\" to be light, easy to run on potato, and fun!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "532b4f5c8f7ec9276767b0fbf5def7102042961694b3c11cd399eb2a4f528484"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"
