name = "InShittingRev2"
author = "CanInBad"
version = "r1"
description = "A general modpack \"designed\" to be light, easy to run on potato, and fun!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fc837ac5daec2ee36448a781b2aa8c34841ce9380c1fda5fd9d5b437d2f191b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"
